### ISSUE TITLE
Current CPAN version has old t/00-compile.t - release with latest?

### ISSUE THREAD

**Issue by mohawk2** [dagolden/types-path-tiny#7]
On "perl in space" the current `t/00-compile.t` fails. Could you release with current `Dist::Zilla::Plugin::Test::Compile`?

**Comment by mohawk2** [comment]
@xdg As discussed on IRC just now, ping!

**Comment by karenetheridge** [comment]
\#oslo

**Comment by xdg** [comment]
Shipped to CPAN as 0.006.
